language: generic
sudo: required
services:
  - docker

before_install:
  - docker --version
  - chmod +x setup.sh
  - bash setup.sh -de
  - docker-compose up -d
  - docker ps -a

before_script:
  - sleep 240

script:
  - docker exec meteor_php /bin/bash -c "cd /var/www; ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests"
