services:
  - docker

before_install:
  - chmod +x setup.sh
  - bash setup.sh -de
  - docker-compose up
  - docker ps -a

script:
  - docker exec meteor-car-dealership_php_1 \
      bash -c \
      "cd /var/www; \
      ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests"
