web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./web:/var/www/
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./web:/var/www/
composer:
    image: composer/composer:php7
    command: install -d=/var/www/
    volumes:
        - ./web:/var/www/

