version: "3.3"
services:
    web:
        container_name: meteor_nginx
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./web:/var/www/
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
            - database
    php:
        container_name: meteor_php
        build: ./docker/php
        volumes:
            - ./web:/var/www/
    composer:
        container_name: meteor_composer
        image: composer:latest
        command: install -d /var/www/
        volumes:
            - ./web:/var/www/
    database:
        container_name: meteor_oracle
        image: oracle/database:11.2.0.2-xe
        environment:
            - ORACLE_ALLOW_REMOTE=true
        shm_size: 1gb
        volumes:
            - type: volume
              source: db-data
              target: /u01/app/oracle/oradata
            - ./oracle/setup:/u01/app/oracle/scripts/setup
            - ./oracle/startup:/u01/app/oracle/scripts/startup
        ports:
            - 1521:1521
            - 8081:8080
            - 5500:5500
volumes:
    db-data:
