ALTER DATABASE DEFAULT TABLESPACE USERS;
CREATE USER dlee IDENTIFIED BY Hunter2;

GRANT CONNECT,
      CREATE TABLE,
      CREATE VIEW,
      CREATE PROCEDURE,
      CREATE SEQUENCE
   TO dlee;

ALTER USER dlee QUOTA UNLIMITED ON USERS;

